### ISSUE TITLE
Overlay characters unreadable

### ISSUE THREAD

**Issue by svenax** [adrian-budau/easy-motion#7]
I have not used Atom for a while, so I'm not sure when this change was introduced.

The overlay characters are placed under the normal text, making them almost unreadable. Easily fixed by setting `z-index: 9999` or similar. I also think it works better if the overlay background color stands out a little. Using `@syntax-selection-color` instead of `@syntax-background-color` works for me.

**Comment by jmacdonald** [comment]
Also experiencing this issue on the latest version.

**Comment by adrian-budau** [comment]
Thanks for the feedback, fixed this bug just now.

**Comment by jmacdonald** [comment]
Looks great!

Very small issue, but it looks like the background colour has some transparency to it that allows the text underneath to bleed through:

![screenshot 2015-01-09 11 24 26](https://cloud.githubusercontent.com/assets/458253/5683008/570a50d8-97f2-11e4-8283-72f94b65218f.png)
